### ISSUE TITLE
can't clone the repository from forked 

### ISSUE THREAD

**Issue by HridoyHazard** [lionelsamrat10/LeetCode-Solutions#117]
i forked this repository but can't clone it. tried in git bash the folder is empty and git desktop giving error.

**Comment by lionelsamrat10** [comment]
Show me the error you're getting

**Comment by HridoyHazard** [comment]
![image](https://user-images.githubusercontent.com/71395891/142343461-4e4100e5-cd02-46c5-95e7-fef01298e906.png)

**Comment by lionelsamrat10** [comment]
Try with 
git clone https://github.com/lionelsamrat10/LeetCode-Solutions.git through your Git Bash once.

**Comment by HridoyHazard** [comment]
![image](https://user-images.githubusercontent.com/71395891/142432291-71418c0e-6c5f-4938-b68a-7e9853861d31.png)
showing this

**Comment by lionelsamrat10** [comment]
Clone it in a different folder. It'll work!!

**Comment by HridoyHazard** [comment]
![image](https://user-images.githubusercontent.com/71395891/142563585-dbfb7585-a55e-4f1b-9f1e-a06d9235b3d5.png)
Folder is empty :/

**Comment by lionelsamrat10** [comment]
Checkout is getting falied !!

**Comment by HridoyHazard** [comment]
why is this happening ?? what's the solution for this ?
