### ISSUE TITLE
450. Delete Node in a BST

### ISSUE THREAD

**Issue by sRahul-00** [lionelsamrat10/LeetCode-Solutions#77]
I would like to add this one.
Link: https://leetcode.com/problems/delete-node-in-a-bst/

**Comment by Karthiks08** [comment]
I want to work on this issue

I am currently preparing for my intern preparations and it would help me a lot , please do the needful and assign me this problem

Please assign me @omkarnayak @lionelsamrat10 @shubhamshettyy @kushal13112001 @viraj-v1112
